### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'model'

### ISSUE THREAD

**Issue by takao-s** [team4gentleman/chainerapp#7]
DLを実行するとエラーが発生する

```
root@6d875f79a8e5:/opt/t4j/chainerapp# ./dlbin/dl_2_training.sh 
epoch 1
learning rate 0.01
epoch 2
learning rate 0.0097

epoch 3
learning rate 0.009409
epoch 4
learning rate 0.00912673
epoch 5
learning rate 0.0088529281
Traceback (most recent call last):
  File "./nurse_train.py", line 272, in <module>
    train_loop()
  File "./nurse_train.py", line 258, in train_loop
    pickle.dump(model, open('%s/model%04d'%(args.model,epoch_count), 'wb'), -1)
AttributeError: 'Namespace' object has no attribute 'model'
```

**Comment by naokiiiii** [comment]
おお！直ってる！
動作確認しました。ありがとうございます。
